#!/usr/bin/env python3
import sys
from src.package_chain import PackageChain
from src.environment import BuildContext

if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Usage ", sys.argv[0], "package-name[features]:branch")
        sys.exit(-1)

    BuildContext.add("debug_build")
    PackageChain(sys.argv[1]).build()
