#!/usr/bin/env python3
import argparse

from src.environment import BuildContext
from src.package_chain import PackageChain

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("pkg", help="package-name[features]:branch")
    parser.add_argument("-j", type=int, default=1, help="parallel job number")

    args = parser.parse_args()
    BuildContext.add("debug_build")
    PackageChain(args.pkg).build(parallel=args.j)
