#!/usr/bin/env python3
import sys
import os
from src.package_chain import PackageChain

if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Usage ", sys.argv[0], "package-name[features]:branch")
        sys.exit(-1)

    PackageChain(sys.argv[1]).build()
