#!/usr/bin/env python3
import argparse

from src.environment import BuildContext
from src.package_chain import PackageChain

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("pkg", help="package-name[features]:branch")
    args = parser.parse_args()

    PackageChain("docker_env:master").build()

    BuildContext.add("docker")
    BuildContext.add("cuda_docker")
    BuildContext.target_system = "ubuntu"
    PackageChain(args.pkg).build_docker()
